// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "KikiTheWizard",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "KikiTheWizard",
            targets: ["AppModule"],
            bundleIdentifier: "com.LarissaOkabayashi.KikiTheWizard",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.purple),
            supportedDeviceFamilies: [
                .pad,
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .copy("media")
            ]
        )
    ]
)
